### ISSUE TITLE
Difference between SurgicalDINO and EndoDAC

### ISSUE THREAD

**Issue by leoyala** [BeileiCui/SurgicalDINO#5]
Hello, 

I was wondering what are the main differences between this project and your EndoDAC model. I see that both aim to estimate depth from surgical images, but I am not sure which advantages/disadvantages each has. I would appreciate it if you could clarify that.

**Comment by BeileiCui** [comment]
Of course

1.
SurgicalDINO was meant to be a supervised method(although we also test the model with SSL method) that requires depth ground truth to be fine-tuned. 
EndoDAC is meant to be a SSL method where we estimate depth, ego-motion and intrinsic at the same time. Therefore Endodac technically only requires surgical frames to be trained.

2. 
Surgical-DINO only utilizes vanilla LoRA to fine-tune the model.
We design DV-LoRA for EndoDAC to fine-tune with fewer Lora parameters when training. We also added residual necks to solve for the neglection of high-frequency information. We also utilize a DPT-liked multi-head depth head for EndoDAC while SurgicalDINO only has a simple linear layer for depth head.

I would say EndoDAC is more focused on an overall Mocular depth estimation SSL method. EndoDAC has more generalization ability because you only need image frames to fine-tune it. EndoDAC shows much better qualitative results and quantitative results.

**Comment by leoyala** [comment]
Thank you for the detailed description @BeileiCui! 👍🏼
